### ISSUE TITLE
GeoLite2 will not have lat/long in 2019

### ISSUE THREAD

**Issue by gfr10598** [m-lab/downloader#17]
See related issue in ETL repo.  
https://github.com/m-lab/etl/issues/389

**Comment by gfr10598** [comment]
Looks like we may need to worry about updates in 2Q2018, and need to look at downloader updates real soon.
Probably need to migrate to GeoIP2 in second half of the year.

**Comment by nkinkade** [comment]
It seems that [Maxmind reconsidered](https://dev.maxmind.com/geoip/geoip2/geolite2/) and lat/lon will remain in the GeoLite2 databases after all:

> **Note**: After careful consideration, taking into account customer feedback, we have decided against removing latitude and longitude coordinates from the GeoLite2 databases. We are in the process of reviewing coordinates used in all of our GeoLite2 and GeoIP databases to ensure there is no risk of misuse.

**Comment by pboothe** [comment]
Hooray!

**Comment by kokosta** [comment]
Fixed
