### ISSUE TITLE
Move downloader deployments to the data-processing-cluster

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/downloader#18]
The data-processing-cluster should contain services generally related to data processing, such as the downloader. In particular, the downloader does not need it's own dedicated cluster.

This task would move the downloader deployment to data-processing-cluster and retire the downloader cluster. As well, the deployments to the downloader cluster in prometheus-support should also be removed.

**Comment by gfr10598** [comment]
Part of Story: https://github.com/m-lab/etl/issues/389

**Comment by stephen-soltesz** [comment]
mlab-sandbox deployment "Expiring Google Kubernetes Engine Certificate" in the next 4 months.

This could be motivation to move the deployment to the data-processing-cluster.

**Comment by yachang** [comment]
mini steps to the goal:

1. move 

kubectl create secret generic \
    downloader-app-key --from-file=key.json=/path/to/key.json

to deployment shell since we have already added new ENV variable in travis

**Comment by yachang** [comment]
2. create secret for Maxmind Licence Key as well from travis ENV variable, so it can be used for downloading.

**Comment by yachang** [comment]
3. Update k8s deployment config to use new secrets.

**Comment by yachang** [comment]
4. Updating the maxmind.go code to use the license key from k8s ENV

**Comment by stephen-soltesz** [comment]
@yachang  completed this!
