### ISSUE TITLE
Create a "current" directory for static download targets

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/downloader#19]
mlab-ns recently updated the GeoLite2 db used for IP-to-location information. The data that downloader downloads should also be placed in a static location like "current" in addition to the per-date locations it already creates.

Current:
https://storage.googleapis.com/downloader-mlab-oti/Maxmind/2018/05/01/20180501T042357Z-GeoLiteCity.dat.gz

For example:
https://storage.googleapis.com/downloader-mlab-oti/Maxmind/current/GeoLiteCity.dat.gz

**Comment by stephen-soltesz** [comment]
@pboothe -- this also covers the uuid-annotator use-case. Glad that I had the same though today as I did in 2018.

**Comment by stephen-soltesz** [comment]
Part of https://github.com/m-lab/dev-tracker/issues/549

**Comment by stephen-soltesz** [comment]
@yachang downloader should do this automatically.

**Comment by stephen-soltesz** [comment]
Looks like this should also apply to the latest RouteViews data also.

**Comment by stephen-soltesz** [comment]
The downloader should create "current" files similar to the following URLs used by the uuid-annotator in k8s-support:

```
-maxmind.url gs://downloader-mlab-sandbox/Maxmind/current/GeoLite2-City.tar.gz
-routeview-v4.url gs://downloader-mlab-sandbox/RouteViewIPv4/current/routeview.pfx2as.gz
-routeview-v6.url gs://downloader-mlab-sandbox/RouteViewIPv6/current/routeview.pfx2as.gz
```

**Comment by yachang** [comment]
We should automate the update of this "current" dir as well.
