### ISSUE TITLE
Create Maxmind account for datasets downloading

### ISSUE THREAD

**Issue by yachang** [m-lab/downloader#36]
Due to recent maxmind EULA change.

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

https://www.maxmind.com/en/geolite2/eula

**Comment by critzo** [comment]
Account has been created and added to shared-data repo. PR: https://github.com/m-lab/shared-data/pull/32

**Comment by pboothe** [comment]
Thanks!
